config/routes.rb
VimWeekly::Application.routes.draw do
  
  resources :admin
  resources :issues
  resources :sessions, only: [:new, :create, :destroy]

  root to: "issues#home"

  get "about", to: "issues#about"
  get "new_entry", to: "issues#new_entry"

  get "tawtaw", to: "sessions#new"
  get "signout", to: "sessions#destroy"

  get "issues", to: "issues#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

  before_save :downcase_email

  VALID_REGEX = /\A[\w+@\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :email, presence: true, format: { with: VALID_REGEX },
    uniqueness: { case_sensitive: false }
  validates :name, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_digest, presence: true

  private
  def downcase_email
    self.email.downcase 
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base

  has_many :tip

end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :issue
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end

  def show
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params[:admin])
    if @admin.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include IssuesHelper

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :signed_in_admin, only: [:new_entry, :create]

  def new
  end

  def index
    # put desc in the order clause if you change your mind
    @issues = Tip.joins("INNER JOIN issues on issue_id = issues.id")
    .select("tips.summary, tips.code, tips.description, issues.*, issues.id").order("issue_id desc")
    respond_to do |format|
      format.html
      format.xml  { render "index.xml.erb", :content_type => 'application/xml' }
      format.json  { render "index.json.erb", :content_type => 'application/json' }
    end
  end

  def create
    @new_entry = Issue.new(issue_param)
    if @new_entry.save
      flash[:success] = "New entry added"
      redirect_to root_url
    else
      flash[:error] = "Submission failed!"
      render 'new_entry'
    end
  end

  def show
    begin
      @issue = Issue.find(params[:id])
      issue_db_values(params[:id])
    rescue ActiveRecord::RecordNotFound
      return render 'not_found'
    end
  end

  def about
  end

  def new_entry
  end

  def home
    @issue = Issue.last
    issue_db_values(Issue.last.id)
  end

  def issue_db_values(id)
    @issue_number = id
    @issue_release_date = Issue.find(@issue_number).release_date
    @tip_val = Issue.find(id).tip
  end


  private
  # This is to allow mass assignment
  def issue_param
    params.require(:tip).permit(:author, :code, :summary,
                                :description)
  end

  def signed_in_admin
    redirect_to root_path unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by_email(params[:session][:email])
    if admin && admin.authenticate(params[:session][:password])
      sign_in admin
      redirect_to url_for(:controller => :issues, 
                                      :action => :new_entry), :notice => "Logged in!"
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path    
  end

  def entry
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
        #<summary><%= replace_special_chars val.summary.to_s %></summary>
        #<pubDate><%= Date.parse(val['release_date']).rfc2822%></pubDate>
        #<code><%= replace_special_chars val.code.to_s %></code>
        #<description><%= replace_special_chars val.description.to_s %></description>
        #&lt;p&gt;&lt;code&gt;<%= val.code %>&lt;/code&gt;&lt;/p&gt;
        #&lt;p&gt;<%= val.description %>&lt;/p&gt;
  def replace_special_chars input
    final = ""
    input.each_char do |x|
      if x == ">"
        final << "&gt;"
        next
      end
      if x == "<"
        final << "&lt;"
        next
      end
      final << x
    end
    final
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(admin)
    cookies.permanent[:admin_id] = admin.id
    self.current_admin = admin
  end

  def current_admin=(admin)
    @current_admin = admin 
  end

  def current_admin
    @current_admin ||= Admin.find_by_id(cookies[:admin_id])
  end

  def signed_in?
    !current_admin.nil?
  end

  def sign_out
    self.current_admin = nil
    cookies.delete(:admin_id)
  end
end

app/views/admin/index.html.erb
<div class="row" >
  <div class="span10 pagination-centered">
    <div class="div-on-left">
      <h4>Sorry contact the admin if you want an account to be created</h4>
    </div>
  </div>
</div>

app/views/admin/show.html.erb
<div class="row" >
  <div class="span10 pagination-centered">
    <div class="div-on-left">
      <h3>Admin Panel</h3>
      <h2>Add an entry to the database</h2>
      <div class="panel-body">
        <form accept-charset="UTF-8" role="form">
          <fieldset>
            <div class="form-group">
              <input class="form-control" placeholder="E-mail" name="email" type="text">
            </div>
            <div class="form-group">
              <input class="form-control" placeholder="Password" name="password" type="password" value="">
            </div>
            <div class="form-group">
              <input class="btn  btn-success" type="submit" value="Create">
            </div>
          </fieldset>
        </form>
      </div>

    </div>

  </div>

</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="span5">
    <div class="div-on-left">
      <h1>Five vim tips for your week</h1>
      <br/>
      <p>Vim is awesome, fun and powerful! Vim has lots of hidden features that we
      don't use. Every monday, we send 5 tips that can help boost your vim productivity
      you can think of it as one tip per day!</p>
      <br/>
      <a href="archives.html" class="btn btn-success btn-large btn-wide">
        View Archives<br/>
        <small>Past issues of vim-weekly</small>
      </a>
    </div>
  </div>
  <div class="span5">
    <!-- can contain a video, image, etc-->
    <img src="/assets/vim-editor_logo.png" alt="code environment"/>
    <!-- <iframe src="http://player.vimeo.com/video/1970676?title=0&amp;byline=0&amp;portrait=0" width="500" height="282"></iframe> -->
  </div> 
</div><!-- end of inner .row-->

<br/>

<br/>
<div class="row">
  <div class="span9 offset40px">
    <div class="well email-subscribe">
      <div id="mc_embed_signup" class="center-align">
        <form action="http://pizzabox.us4.list-manage.com/subscribe/post?u=3b47a1485e96c3923dccb1e5a&amp;id=c6499cc83d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank">
          <label for="mce-EMAIL">Already integrated with <em>MailChimp</em> accounts:</label>
          &nbsp;
          <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" >
          &nbsp;
          <input type="submit" value="Subscribe!" name="subscribe" id="mc-embedded-subscribe" class="btn btn-success">
        </form>
      </div>
      <!--End mc_embed_signup-->
    </div>
  </div>
</div>

<br/>



<div class="row">
  <div class="span10">
    <div class="div-on-left">
      <h4><a href="Issue 1">Issue #1 — January 18, 2014</a></h4>
      <br/>
      <strong> <p>Tip 1</p></strong>
      <br/>
      <strong> <p>Tip 2</p></strong>
      <br/>
      <strong> <p>Tip 3</p></strong>
      <br/>
      <strong> <p>Tip 4</p></strong>
      <br/>
      <strong> <p>Tip 5</p></strong>
      <br/>
    </div>
  </div>
</div>

app/views/issues/_issue.html.erb
<div class="issue_area">
  <h4><a href="/issues/<%= @issue_number %>">Issue #<%= @issue_number %> - <%= @issue_release_date %>    </a> <a href="https://twitter.com/share" class="twitter-share-button" data-via="vimweekly">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></h4>
  <br/>
<% @tip_val.each_with_index do |c, i|%>
  <strong> <p>Tip <%= i+1 %></p></strong>
  <p>
  <%= c.description %>
  </p>
  <pre id='vimCodeElement'><%= c.code %>
  </pre>
  <div class="span3 author">
    <p> <strong>Source: </strong> <%= c.author %> </p>
  </div>
  <br/>
<% end %>
</div>

app/views/issues/about.html.erb
<div class="div-on-left">
  <h3>About</h3>
  <p>Vim Weekly is heavily based on community input, blogs, stackoverflows, books, dot files as well as the the ultimate vim manual. <a href="https://github.com/tawrahim/">Tawheed Raheem</a> serves as the door to this amazing project. </p>
  <br />
  <h3>Credit</h3>
  <p>To see clickable links to the author/sources of all the tips see the <a href="https://github.com/vimweekly/tips/blob/master/PUBLISHED.md">published tips</a> page on github</p>
  <br />
  <h3>Contributing</h3>
  <p>If you think you have discovered a tip that the community might benefit, please modify the <a href="https://github.com/vimweekly/tips/blob/master/TO_BE_PUBLISH.md">TO_BE_PUBLISH.md</a> file on github</p>
  <p>You can also tweet or send an email to us!</p>
</div>

app/views/issues/home.html.erb
<div class="row">
  <div class="span5">
    <div class="div-on-left">
      <h1>Five vim tips for your week</h1>
      <br/>
      <p>Vim is awesome, fun and powerful! Vim has lots of hidden features that we
      don't use. Every monday, we send 5 tips that can help boost your vim productivity
      you can think of it as one tip per day!</p>
      <br/>
      <a href="/issues" class="btn btn-success btn-large btn-wide">
        View Archives<br/>
        <small>Past issues of vim-weekly</small>
      </a>
    </div>
  </div>
  <div class="span5">
    <img src="/assets/vim-editor_logo.png" alt="code environment"/>
  </div> 
</div><!-- end of inner .row-->

<br/>

<br/>
<div class="row">
  <div class="span9 offset40px">
    <div class="well email-subscribe">
      <div id="mc_embed_signup" class="center-align">
        <form action="http://tawheedraheem.us5.list-manage1.com/subscribe/post?u=6ad5cec1778231d2289e8a142&amp;id=e7b2432770" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank">
          <label for="mce-EMAIL">Five vim tips brewed every Monday's to your mailbox</label>
          &nbsp;
          <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" >
          &nbsp;
          <input type="submit" value="Subscribe!" name="subscribe" id="mc-embedded-subscribe" class="btn btn-success">
          <input type="button" onclick="location.href='http://www.vimweekly.com/issues.xml'" value="RSS" name="subscribe" id="mc-embedded-subscribe" class="btn btn-warning">
        </form>
      </div>
      <!--End mc_embed_signup-->
    </div>
  </div>
</div>

<br/>

<!-- we need to use a partial here -->

<%#<div class="announcement" style="background-color: #FCF0AD;border-bottom-left-radius: 1px;border: 1px solid #eec;border-radius: 5px;margin-bottom: 17px;color: #505050;font-family: Arial;font-size: 14px;line-height: 150%;text-align: left;">%>
<%#<p style="margin-left: 8px;">Aloha vimmers! My big apologies for not publishing tips the past two weeks, we&#39;ve been busy at work trying to get a release&nbsp;out to QA. Vim Weekly is back in full swing and you should be expecting awesome tips delivered in&nbsp;your mailbox on Sundays!<br>%>
<%#<br>%>
<%#<strong>NOTE</strong>:<br>%>
<%#Vim Weekly is community driven and it is highly influenced by the tips you send, so please don&#39;t hesitate to send that productivity booster you use on a daily basis.<br>%>
<%#Finally as we all know Vim Weekly is an open source project and will always remain FREE from ads forever.&nbsp;Now&nbsp;to prevent the&nbsp;hiatus that happened the past couple of weeks I would like other members to help with the publications/ have write access to the project -&nbsp;Just incase I get hit by a bus :-)&nbsp;<br>%>
<%#<br>%>
<%#- Tawheed</p>%>
<%#</div>%>
<div class="row">
  <div class="span10">
    <div class="div-on-left">
      <%= render 'issue' %>
    </div>
  </div>
</div>

app/views/issues/index.html.erb
<h1 class="div-on-left">Archives</h1>
<div class="row">
  <div class="span5">
    <div class="div-on-left">
<% 
  id = 0 
  @issues.each do |x|
    if (id != x.id)
  %>
  <h4><a href="issues/<%= x.id %>">Issue # <%= x.id %> — <%= x['release_date'] %></a></h4>
  <% 
     id = x.id
    end
  %>
<ul>
  <li>
  <%= x.summary %>
  </li>
</ul>
  <% end %>
    </div>
  </div>
  <br />
</div> <!-- end of row -->

app/views/issues/index.json.erb
<% @issues.each do |x| %>
<% end %>
{
"Issue #<%= %>": [
{ "tip_number":""}, 
{ "summary":""}, 
{ "code":"" },
{ "description":""  }
]
}

app/views/issues/index.xml.erb
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <title>Vim Weekly</title>
    <link>http://www.vimweekly.com/</link>
    <description>5 vim tips every Mondays</description>
    <% @issues.each do |val| %>
      <item>
        <title><%= val.summary %></title>
        <pubDate><%= Date.parse(val['release_date']).rfc2822%></pubDate>
        <description>
          <%= replace_special_chars val.code.to_s %>
        <%= replace_special_chars val.description.to_s %>
        </description>
      </item>
    <% end %>
  </channel>
</rss>

app/views/issues/new.html.erb
<h1>Issues#new</h1>
<p>Find me in app/views/issues/new.html.erb</p>

app/views/issues/new_entry.html.erb
<div class="row" >
  <div class="span10 pagination-centered">
    <div class="div-on-left">
    <h3>Enter your weekly tips!</h3>
      <div class="panel-body">
       <%= form_for(:issues, url: issues_path)  do |f| %>
           <%= f.text_area(:tip1, placeholder: "email")%>
           <br />
           <%= f.text_area(:tip2, placeholder: "email")%>
           <br />
           <%= f.text_area(:tip3, placeholder: "email")%>
           <br />
           <%= f.text_area(:tip4, placeholder: "email")%>
           <br />
           <%= f.text_area(:tip5, placeholder: "email")%>
           <br />
           <%= f.text_field(:release_date, placeholder: "email")%>
           <br />
           <%= f.submit "submit", class: "btn btn-success" %>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/issues/not_found.html.erb
<div class="div-on-left">
  <h4>Issue does not exists!</h4>
</div>

app/views/issues/show.html.erb
<div class="row">
  <div class="span10">
    <div class="div-on-left">
      <%= render 'issue' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vim Weekly</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Gentium+Book+Basic|Leckerli+One|Abril+Fatface|Merriweather:400,900|Patua+One|Lato:300,400' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <style type="text/css">
      <!--
      pre { white-space: pre-wrap; font-family: monospace; color: #d0d0d0; background-color: #121212; }
      .Operator { color: #d7005f; }
      .Comment { color: #5f5f5f; }
      .Statement { color: #d7005f; font-weight: bold; }
      .Delimiter { color: #626262; }
      .Identifier { color: #ff8700; }
      .issue_area { width: 850px; }
      -->
      .announcement{
        background-color:#FCF0AD;
        border-bottom-left-radius:1px;
        border:1px solid #eec;
        border-radius:5px;
        margin:25px;
      }
      .announcement>p{
        margin-left:8px;
      }
    </style>
    <link rel="icon" href="/assets/vim-editor_logo.png">
  </head>
  <body class="gridbg">
    <div class="container">
      <a id="header" href="/"><h1 id="logo">vim-weekly</h1></a>
      <br/>
      <div class="row">
        <div id="main" class="span10 offset1">

          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash#{name}" %>
          <% end %>
          <% if signed_in? %>
            <p><%= link_to "Sign out", signout_path  %></p>
          <% end %>
          <%= yield %>

          <div class="row">
            <div class="span10 footer">
              <div class="row">
                <div class="span4  contact">
                  <strong>Got a cool tip?:</strong> send us an <a href="mailto:vim.weekly@gmail.com?Subject=Vim%20Tip%20Suggestion" target="_top">
                    email </a> or tweet us!
                </div>

                <div class="span5 social_icons">
                  <a href="https://twitter.com/intent/tweet?screen_name=vimweekly" class="twitter-mention-button" data-related="vimweekly">Tweet to @vimweekly</a>
                  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                  <a href="https://twitter.com/vimweekly" class="twitter-follow-button" data-show-count="false">Follow @vimweekly</a>
                  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                </div>
              </div>
            </div>
          </div>

        </div><!-- end of .span10-->
        <br/>
      </div><!-- end of .row-->
      <br/>
      <div class="copyright center-align">
        &copy; Vim Weekly - 2014 | <a href="/about">About</a> | <a href="/issues">Archives</a>
      </div>
    </div> <!-- /container -->
    &nbsp;
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>